# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    http_client:
        scoped_clients:
            sms.client:
                base_uri: '%env(SEND_SMS_EXTERNAL_API_URL)%'
                headers:
                    - name: 'X-API-KEY'
                      value: '%env(SMS_SERVICE_API_KEY)%'
                # ...
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
