security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        email_user_provider:
            entity:
                class: App\Entity\User
                property: email
        token_user_provider:
            entity:
                class: App\Entity\User
                property: apiToken
    role_hierarchy:
        ROLE_ADMIN: [ ROLE_USER, ROLE_TRAINER ]
        ROLE_TRAINER: ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            provider: email_user_provider
            logout:
                path: admin_logout
                target: admin_login
            form_login:
                login_path: admin_login
                check_path: admin_login
                enable_csrf: true
                default_target_path: admin_dashboard
        main:
            lazy: true
            provider: token_user_provider
            stateless: true
            custom_authenticators:
                - App\Authenticator\TokenAuthenticator
            json_login:
                check_path: api_programmes_login
            http_basic:
                realm: Secured Area

    access_control:
        - { path: '^/admin/login', roles: PUBLIC_ACCESS }
        - { path: '^/admin', roles: ROLE_ADMIN }
        - { path: '^/api/users/register', roles: PUBLIC_ACCESS }
        - { path: '^/api/login', roles: PUBLIC_ACCESS }
        - { path: '^/api/messages', roles: ROLE_ADMIN }
        - { path: '^/api', roles: ROLE_ADMIN }
        - { path: '^/', roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
