controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

controllers_admin:
    resource: ../../src/Controller/Admin/
    type: annotation
    prefix: '/admin'
    name_prefix: 'admin_'