parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $programmeMinTime: '%env(PROGRAMME_MIN_TIME_IN_MINUTES)%'
            $programmeMaxTime: '%env(PROGRAMME_MAX_TIME_IN_MINUTES)%'
            $programmesApiUrl: '%env(EXTERNAL_PROGRAMMES_API_URL)%'
            $maxProgrammesPerPage: '%env(MAX_PROGRAMMES_PER_PAGE)%'
            $apiVersion: '%env(API_VERSION)%'
            $analyticsLogPath: '%env(ANALYTICS_LOG_PATH)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Message/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ "controller.service_arguments" ]

    App\EventSubscriber\AdminLoginSubscriber:
        tags:
            - name: kernel.event_subscriber
              dispatcher: security.event_dispatcher.admin

    App\EventSubscriber\ApiLoginSubscriber:
        tags:
            - name: kernel.event_subscriber
              dispatcher: security.event_dispatcher.api
